name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.x.x/x64  # Ensures the correct JDK path
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk  # Correct path for the SDK in GitHub Actions

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'  # OpenJDK distribution
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2  # Installs SDK, builds tools, and platform tools
      with:
        api-level: 30
        build-tools: '30.0.3'

    - name: Download dependencies
      run: ./gradlew build --no-daemon

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest --no-daemon  # Ensures the correct variant is specified

    - name: Run Android instrumented tests
      run: ./gradlew connectedAndroidTest --no-daemon

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: app/build/reports/tests/connected/
